GuessResult/Controllers/EventController.cs
using GuessResult.DB.Models;
using GuessResult.Helpers;
using GuessResult.Models;
using GuessResult.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuessResult.Controllers
{
    public class EventController : Controller
    {
        public ActionResult EventList()
        {
            try
            {
                return View(new EventListViewModel());
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
    }
}

GuessResult/Controllers/NewsFeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuessResult.Controllers
{
    public class NewsFeedController : Controller
    {
        // GET: NewsFeed
        public ActionResult Index()
        {
            return View("NewsFeedList");
        }
    }
}

GuessResult/Controllers/UserController.cs
using GuessResult.Helpers;
using GuessResult.Models;
using GuessResult.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using GuessResult.DB.Models;
using GuessResult.Enum;
using System.Net;
using System.Security.Claims;
using Microsoft.Owin.Security.OAuth;
using static GuessResult.Startup;
using System.Threading.Tasks;
using GuessResult.Repositories.Interfaces;

namespace GuessResult.Controllers
{
    public class UserController : Controller
    {
        //private IUserRepository _userRepository;


        //public UserController()
        //{
        //}

        //public UserController(IUserRepository userRepository)
        //{
        //    _userRepository = userRepository;
        //}

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            try
            {
                return View("Login");
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [HttpGet]
        public ActionResult GetAllStatiscics()
        {
            try
            {
                return View("Statistics");
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
        [HttpGet]
        public ActionResult GetAllStatiscicsUsers()
        {
            try
            {
                return View("MainStatistics");
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model)

        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    var result = new ApplicationSignInManager(HttpContext.GetOwinContext()).PasswordSignIn(model);

                    switch (result)
                    {
                        case SignInStatus.Success:
                            return RedirectToAction("Index", "Home");

                        case SignInStatus.LockedOut:
                        case SignInStatus.RequiresVerification:
                        case SignInStatus.Failure:
                        default:
                            ModelState.AddModelError("Haslo", "Niepoprawny login lub hasło");
                            return View("Login", model);
                    }

                }
                else
                {
                    return View("Login", model);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }

        }
        [HttpGet]
        public ActionResult Register()
        {
            return View("Register");
        }

        [HttpPost]
        public ActionResult LogOff()
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    if (Request.IsAuthenticated == true)
                    {
                        Session.Abandon();
                        HttpContext.GetOwinContext().Authentication.SignOut();
                    }
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }


        [HttpPost]
        public ActionResult ExternalLogin(string provider)
        {
            // Request a redirect to the external login provider
            return new ChallengeResult(provider, Url.Action("ExternalLoginCallback"));
        }

        public async Task<ActionResult> ExternalLoginCallback()
        {
            var loginInfo = await HttpContext.GetOwinContext().Authentication.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                return RedirectToAction("Index", "Home");
            }


            var result = new ApplicationSignInManager(HttpContext.GetOwinContext()).ExternalLogin(loginInfo.Email, loginInfo.DefaultUserName);

            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToAction("Index", "Home");

                case SignInStatus.LockedOut:
                case SignInStatus.RequiresVerification:
                case SignInStatus.Failure:
                default:
                    return RedirectToAction("Index", "Home");
            }
        }

        [AllowAnonymous]
        public ActionResult ExternalLoginFailure()
        {
            return View();
        }
    }
}

GuessResult/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/js")

    <script>
        $(document).ready(function () {
            $('.input-group.date-time').datetimepicker({
                locale: 'pl',
                format: 'YYYY-MM-DD HH:mm'
            });
            $('.input-group.date-time').on("dp.change", function (e) {
                $(this).find('input').val(e.date.format('YYYY-MM-DD HH:mm')).trigger('change');
            });


            $('.input-group.date').datetimepicker({
                locale: 'pl',
                format: 'YYYY-MM-DD'
            });
            $('.input-group.date').on("dp.change", function (e) {
                $(this).find('input').val(e.date.format('YYYY-MM-DD')).trigger('change');
            });

        });
    </script>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
</head>
@if (User.Identity.IsAuthenticated)
{
    <body class="inner">
        <div id="wrapper">
            <div class="overlay"></div>
            <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper">
                <ul class="nav sidebar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    <li>@Html.ActionLink("Wydarzenia", "EventList", "Event")</li>
                    <li>@Html.ActionLink("Statystyki", "GetAllStatiscics", "User")</li>
                    <li>@Html.ActionLink("Statystyki ogólne", "GetAllStatiscicsUsers", "User")</li>
                    <li>@Html.ActionLink("Nowości ", "Index", "NewsFeed")</li>
                    <li class="liForm">@Html.Partial("_LoginPartial")</li>
                </ul>
            </nav>

            <div id="page-content-wrapper">
                <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                    <span class="hamb-top"></span>
                    <span class="hamb-middle"></span>
                    <span class="hamb-bottom"></span>
                </button>
                <div class="container body-content">
                    @RenderBody()
                    <footer>
                        <hr />
                        <p>&copy; @DateTime.Now.Year - Przewidywanie wyników</p>
                    </footer>
                </div>
            </div><!--page-content-wrapper-->
        </div><!--wrapper-->

        @RenderSection("scripts", required: false)
    </body>
}
else
{
    <body class="home">
        <div id="wrapper">
            <div class="overlay"></div>

            <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper">

                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav sidebar-nav">
                        <li class="sidebar-brand">
                            @Html.ActionLink("Strona główna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand1" })
                        </li>
                        <li class="liForm">@Html.Partial("_LoginPartial")</li>
                    </ul>
                }
                else
                {
                    <ul class="nav sidebar-nav">
                        <li>@Html.Partial("_LoginPartial")</li>
                    </ul>
                }
            </nav>

            <div id="page-content-wrapper">
                <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                    <span class="hamb-top"></span>
                    <span class="hamb-middle"></span>
                    <span class="hamb-bottom"></span>
                </button>
                <div class="container body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - Przewidywanie wyników</p>
                    </footer>
                </div>
            </div><!--page-content-wrapper-->
        </div><!--wrapper-->

        @RenderSection("scripts", required: false)
    </body>
}

</html>